Updated home page march 8th
LaurierCS/POD1 pull request #4
Opened 2024-03-08 14:06 UTC by anikapatychuk

2024-03-09 20:05 UTC, pabloj2001 requested changes
Love how it's looking so far! The only thing I want to suggest is turning this home page into a class (StatelessWidget) and using it from `main.dart` so we only have one entry point to the app. To do this we'd just have to turn the `main` function in this file into a new class, then delete the `MyHomePage` class in `main.dart` and replace
```
home: const MyHomePage(title: 'Flutter Demo Home Page'),
```
in the `MyApp` class with our new Home class. Let me know if you have any questions about this!

2024-03-09 20:05 UTC, pabloj2001 commented on mobile/voice_journal_app/lib/home.dart
>        home: Scaffold(
To turn this into a class, we'll want to place everything in the `Scaffold` in the `build` function of the class, just like it is right now in the `MyHomePage` class in the `main.dart` file

2024-03-10 15:49 UTC, pabloj2001 requested changes
Great job! Just one last suggestion and then I think we can merge 👍

2024-03-10 15:49 UTC, pabloj2001 commented on mobile/voice_journal_app/lib/main.dart
>  class MyHomePage extends StatefulWidget {
We can remove this class now since it's no longer used.

2024-03-11 00:07 UTC, pabloj2001 requested changes
Very last thing, we should have deleted `_MyHomePageState` along with deleting `MyHomePage` since it isn't used anywhere else

2024-03-11 00:07 UTC, pabloj2001 commented on mobile/voice_journal_app/lib/main.dart
>  class _MyHomePageState extends State<MyHomePage> {
We should remove this class as well since it was only used in `MyHomePage` which we just deleted.

2024-03-12 21:21 UTC, Alec-Hallman approved these changes
Looks great!

2024-03-12 21:29 UTC, pabloj2001 approved these changes
Looks Good to Me! 👍

2024-03-12 21:31 UTC, merged