Recording page
LaurierCS/POD1 pull request #6
Opened 2024-03-10 01:07 UTC by Alec-Hallman

### Created the recording page. 

Users can click the microphone button to start a recording, clicking it again will pause the recording and display a little "saved" icon at the bottom of the screen. Whilst audio is being recorded, a sound wave will appear in the blue box displaying their mic input and the top box shows a sound speed clock as well as the recording status. When the recording page or app is closed, the audio file is accessible in your phone's download folder. The name of the file correlates to the date and time at which the recording was started. This page also features the bottom navigation bar (thanks Anika) and can traverse back and forth between the home page. A little "are you sure?" pop up will appear if the user tries to go to the homepage while recording.

> Notes
The recording page does not feature a stop/save button, as the audio recorder will automatically do so. Instead, I created a little pop-up to communicate when the recording is saved. Any feedback on this would be appreciated, as this still might not be as intuitive as it could be. But I enjoy how un intrusive this system is, require the user to press less buttons.

![image](https://github.com/LaurierCS/POD1/assets/109433535/cafc1dd7-f441-4263-88bb-7f04d7561d49)

2024-03-10 23:59 UTC, pabloj2001 requested changes
Good job on this first PR! There's a few things I think we need to update but we're on the right track.

2024-03-10 23:59 UTC, pabloj2001 commented on mobile/voice_journal_app/android/app/src/debug/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.RECORD_AUDIO" />
While declaring permissions here works for Android, we won't get the permission on iOS devices. A better way to do it is to ask for permissions through Flutter when the record button is clicked: https://stackoverflow.com/a/63480023/4749973

2024-03-10 23:59 UTC, pabloj2001 commented on mobile/voice_journal_app/lib/RecordingPage.dart
> +    bottomNavigationBar: BottomAppBar( //Bottom bar yoinked from Anika's home page (Thanks)
We generally want to avoid having duplicates of code in our project and instead want to reuse as much as possible. Instead of putting the bottom nav here, we'll want to put it in the main file and show the pages as widgets within it.

2024-03-10 23:59 UTC, pabloj2001 commented on mobile/voice_journal_app/lib/home.dart
> +import 'RecordingPage.dart'; //Importing recording page
We seem to be merging changes from other PRs here, this is generally bad practice. I know we need to update this page to add the navigation to the recording page, but let's hold off on it until Anika's home page changes get merged. Sorry if I made it confusing!

2024-03-10 23:59 UTC, pabloj2001 commented on mobile/voice_journal_app/lib/Pages/Alec_Recording.dart
> +import 'package:flutter/material.dart';
I don't think we need another page as a starting point for the app. Let's remove this page if there's no need for it.

2024-03-10 23:59 UTC, pabloj2001 commented on mobile/voice_journal_app/lib/RecordingPage.dart
> +}
There's no need for this starting point in the app since we already have `main.dart` and `RecordingPage` will be called when navigated to.

2024-03-12 23:03 UTC, pabloj2001 approved these changes
Looks Good to Me!

2024-03-14 00:33 UTC, anikapatychuk commented on mobile/voice_journal_app/lib/RecordingPage.dart
not sure if I looked at this at all right but I had a problem were as soon I hit record it paused me and the wouldn't un-pause

2024-03-15 04:07 UTC, TaseskiCS commented
Looks like the functionality works smoothly, great work

2024-03-15 04:15 UTC, TaseskiCS reviewed
Just tested it, also had the unpause issue, but other than that everything works great!

2024-03-15 20:57 UTC, merged